info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T01:58:44.828Z"}
info: Connected to the database. {"timestamp":"2022-07-08T01:58:44.884Z"}
error: 
    status - 500 
    message - Error: Callback must be a function, got [object Object]
    at MongooseError.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\modules\es.error.cause.js:28:43)
    at new MongooseError (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at Function.Model.$handleCallbackError (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findOne (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\mongoose\lib\model.js:2266:19)
    at _callee2$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:19:29)
    at tryCatch (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userRegistration (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:18:30)
    at _callee3$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\controllers\/user.controller.js:51:36) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-08T02:01:08.494Z"}
error: 
    status - 500 
    message - Error: Callback must be a function, got [object Object]
    at MongooseError.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\modules\es.error.cause.js:28:43)
    at new MongooseError (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at Function.Model.$handleCallbackError (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findOne (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\mongoose\lib\model.js:2266:19)
    at _callee2$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:19:29)
    at tryCatch (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userRegistration (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:18:30)
    at _callee3$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\controllers\/user.controller.js:51:36) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-08T02:05:31.712Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:06:36.610Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:06:36.650Z"}
error: 
    status - 500 
    message - Error: user already existed
    at Error.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\modules\es.error.cause.js:28:43)
    at _callee2$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:22:11)
    at tryCatch (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-08T02:06:56.310Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:07:40.437Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:07:40.482Z"}
error: 
    status - 500 
    message - Error: user already existed
    at Error.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\modules\es.error.cause.js:28:43)
    at _callee2$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:22:11)
    at tryCatch (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-08T02:08:30.861Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:09:15.585Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:09:15.653Z"}
error: 
    status - 500 
    message - Error: user already existed
    at Error.<anonymous> (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\core-js\modules\es.error.cause.js:28:43)
    at _callee2$ (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\src\services\/user.service.js:22:11)
    at tryCatch (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\fundooNotes_Backend\fundooNotes_Backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-08T02:12:24.611Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:44:42.495Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:44:45.569Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:53:12.208Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:53:15.153Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:57:47.293Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:57:50.358Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:58:25.117Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:58:28.083Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T02:59:09.614Z"}
info: Connected to the database. {"timestamp":"2022-07-08T02:59:12.598Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:14:16.916Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:14:20.569Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:18:46.053Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:18:49.372Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:19:45.332Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:19:48.451Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:21:35.140Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:21:38.622Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:22:48.282Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:22:51.643Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:25:34.251Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:25:37.529Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:26:54.587Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:26:58.194Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:27:41.190Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:27:44.537Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T07:32:39.384Z"}
info: Connected to the database. {"timestamp":"2022-07-08T07:32:43.820Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T08:55:17.346Z"}
info: Connected to the database. {"timestamp":"2022-07-08T08:55:20.542Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T08:57:30.454Z"}
info: Connected to the database. {"timestamp":"2022-07-08T08:57:34.268Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T08:59:01.279Z"}
info: Connected to the database. {"timestamp":"2022-07-08T08:59:04.584Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T09:05:32.323Z"}
info: Connected to the database. {"timestamp":"2022-07-08T09:05:35.956Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T09:06:01.435Z"}
info: Connected to the database. {"timestamp":"2022-07-08T09:06:05.235Z"}
info: Server started at http://localhost:7000/api/v1/ {"timestamp":"2022-07-08T09:43:42.624Z"}
info: Connected to the database. {"timestamp":"2022-07-08T09:43:46.185Z"}
